resolver: lts-18.18

packages:
- .
- gitlib/gitlib
- gitlib/gitlib-libgit2

extra-deps:
#- gitlib-3.1.3@sha256:7e8f940b380f6155be3bf20be9f363c3bfd3285bd26e0368f406a1c431994598,2935
#- gitlib-libgit2-3.1.2.1@sha256:36bc92f117158440ca69e32051aabdf9df75be8a3fb5f45dff8828898e615a0a,2354
- ginger-0.10.4.0@sha256:7ca26896395fda951443ed3bba5f24fd6036c44167d424e744d1e0c8c6b138fd,3855

ghc-options:
  "gitserve": -Wall -Wcompat -Widentities -Wincomplete-uni-patterns
    -Wincomplete-record-updates -Wredundant-constraints -Wpartial-fields
    -Wmissing-deriving-strategies -Wunused-packages -fno-warn-unused-do-bind
    -fno-warn-orphans

rebuild-ghc-options: true
allow-newer: false
