name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        # Fetch all branches and tags so the tests can see them.
        fetch-depth: 0

    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true

    - uses: actions/cache@v4
      with:
        path: ~/.stack/
        key: ${{ runner.os }}-${{ hashFiles('**/stack.yaml.lock') }}

    - name: Build
      run: |
        stack --no-terminal build

    - name: Run tests
      run: |
        bash test/test.sh

    - name: Check doc generation works
      run: |
        stack run -- -c ./config.dhall -q
